### ISSUE TITLE
[BUG] mssqlmqtt asset - Entered in Idle Mode after a period of time.

### ISSUE THREAD

**Issue by aisquarerbo** [CorefluxCommunity/Coreflux-fluxassets#1]
### Bug Description 🐞

After some hours of system running, which includes some Docker Containers sending data to a database, it stopped writing on the database. After checking all system parts, I restarted only the asset and everything started working again.

I've checked the log file, which had around 1GB, and I've found that for almost all the time during it was giving connection error to the database when running the command configured on asset.
[mssqlmqtt-log-07112023.log](https://github.com/CorefluxCommunity/Coreflux-fluxassets/files/13300782/mssqlmqtt-log-07112023.log)

### Steps to Reproduce 🔄

4 Dockers running with a small piece of code sending a small json with 5 attributes to insert in the database each 15ms. Each docker sends 1 message to 1 topic.

### Expected Behavior ✅

In my opinion, in case of error trying to connect it should retry to connect again. In case of failure of the asset, it should restart in order to continue the workflow.

### Environment 🌐

Other (Please specify in 'Additional Info')

### Asset Type 🧩

MS SQL

### Additional Information ➕

Ubuntu 22.04 LTS

### Terms of Service

- [X] I agree to the terms and conditions

**Comment by HugoAVaz** [comment]
![image](https://github.com/microsoft/dotnet/assets/60146011/e6503e81-e55e-44e3-b7f0-9fd55db5d81e)
It looks like the flux asset is posting at speed. Until it fails to exec stored procedure. 
![image](https://github.com/microsoft/dotnet/assets/60146011/f02e64c7-befd-4832-b732-234c5acd779f)
This is the error before.

quick check it looks like by checking it can occur if :
- do we have somehow NULL value data? and the feedback is missing for null values

**Comment by aisquarerbo** [comment]
As we checked, from the service side publishing the message it is filling all the json topic with data.

**Comment by HugoAVaz** [comment]
Those this occurs with QOS1 ?. It look like the JSON is splitting with 2 events . It might occur because an end of reception didn't occured properly. For this definitely QOS1 is the standard since the server can split the stream .

**Comment by aisquarerbo** [comment]
It is now in QOS1. Can you please take a look on this? So, SQL Server was blocked because lack of memory, and the asset was not writting anything to the database. When I unlocked the SQL Server, allowing it to use more memory, SQL unlocked but the Asset was not writting anything. Only when I restarted the asset it started to write in the database.
[status20231113.log](https://github.com/CorefluxCommunity/Coreflux-fluxassets/files/13336635/status20231113.log)

**Comment by HugoAVaz** [comment]
We were able to make the same scenario but with 10 dockers with 1ms each. And finally reached the same issue.  

Probable Cause:
Our current configuration for the SQL Server connection pool might not be optimized for the scale that which this scenario requires. The Min Pool Size and Max Pool Size settings in our connection are defined by the client itself, and the setting clearly may not be sufficient to handle the volume of concurrent database operations under peak loads.

Proposed Next Steps:

Adjust Connection Pool Settings: We are adapting the Min Pool Size and Max Pool Size settings to better align with our operational requirements. We'll be conducting tests now with different configurations and hardware to find the most optimal settings.

This value is going to be provided in order to work with the configuration of the asset.

**Comment by HugoAVaz** [comment]
Also in the config :
SQL
    | 
    ----->QueryTimeoutInSeconds  -> Set this to bigger than any potential job you have it might affect (like the database time for indexation) typical it is 10 seconds
